apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
      nodePort: 30440
  type: LoadBalancer
